import type { Phrase, VocabularyItem } from '@/types/domain';

// Levels 1-5 are hand-curated by topic (spec 17) and every word there gets
// 3+ phrases across different contexts (spec 7) plus a dialogue. Level 6+ is
// a breadth-first frequency-based vocabulary tail (word count is priority 1,
// level placement is priority 2) with a lighter 2-phrases-per-word shape and
// no dialogue requirement — see the Level 6 section below.
export const vocabulary: VocabularyItem[] = [
  // --- Level 1 — English Foundations ---
  {
    id: 'word-hello',
    word: 'hello',
    partOfSpeech: 'interjection',
    definition: 'used as a greeting when meeting someone or answering the phone',
    pronunciation: '/həˈloʊ/',
    difficulty: 1,
    level: 1,
    topic: 'Greetings',
  },
  {
    id: 'word-goodbye',
    word: 'goodbye',
    partOfSpeech: 'interjection',
    definition: 'used when leaving someone or ending a conversation',
    pronunciation: '/ˌɡʊdˈbaɪ/',
    difficulty: 1,
    level: 1,
    topic: 'Greetings',
  },
  {
    id: 'word-name',
    word: 'name',
    partOfSpeech: 'noun',
    definition: "what a person or thing is called",
    pronunciation: '/neɪm/',
    difficulty: 1,
    level: 1,
    topic: 'Introductions',
  },
  {
    id: 'word-meet',
    word: 'meet',
    partOfSpeech: 'verb',
    definition: 'to see and talk to someone for the first time, or by arrangement',
    pronunciation: '/miːt/',
    difficulty: 1,
    level: 1,
    topic: 'Introductions',
  },
  {
    id: 'word-from',
    word: 'from',
    partOfSpeech: 'preposition',
    definition: 'indicating the place or origin someone or something comes from',
    pronunciation: '/frʌm/',
    difficulty: 1,
    level: 1,
    topic: 'Introductions',
  },
  {
    id: 'word-live',
    word: 'live',
    partOfSpeech: 'verb',
    definition: 'to have your home in a particular place',
    pronunciation: '/lɪv/',
    difficulty: 1,
    level: 1,
    topic: 'Introductions',
  },
  {
    id: 'word-old',
    word: 'old',
    partOfSpeech: 'adjective',
    definition: 'having lived or existed for a long time; used to ask someone\'s age',
    pronunciation: '/oʊld/',
    difficulty: 1,
    level: 1,
    topic: 'Introductions',
  },
  {
    id: 'word-please',
    word: 'please',
    partOfSpeech: 'adverb',
    definition: 'used to make a request more polite',
    pronunciation: '/pliːz/',
    difficulty: 1,
    level: 1,
    topic: 'Courtesy',
  },
  {
    id: 'word-thank-you',
    word: 'thank you',
    partOfSpeech: 'phrase',
    definition: 'used to express gratitude',
    pronunciation: '/ˈθæŋk juː/',
    difficulty: 1,
    level: 1,
    topic: 'Courtesy',
  },
  {
    id: 'word-sorry',
    word: 'sorry',
    partOfSpeech: 'interjection',
    definition: 'used to apologize for something',
    pronunciation: '/ˈsɑːri/',
    difficulty: 1,
    level: 1,
    topic: 'Courtesy',
  },
  {
    id: 'word-today',
    word: 'today',
    partOfSpeech: 'adverb',
    definition: 'on or during this present day',
    pronunciation: '/təˈdeɪ/',
    difficulty: 1,
    level: 1,
    topic: 'Time & Date',
  },
  {
    id: 'word-tomorrow',
    word: 'tomorrow',
    partOfSpeech: 'adverb',
    definition: 'on the day after today',
    pronunciation: '/təˈmɔːroʊ/',
    difficulty: 2,
    level: 1,
    topic: 'Time & Date',
  },
  {
    id: 'word-number',
    word: 'number',
    partOfSpeech: 'noun',
    definition: 'a word or symbol used for counting or identifying, e.g. a phone number',
    pronunciation: '/ˈnʌmbər/',
    difficulty: 2,
    level: 1,
    topic: 'Numbers',
  },

  // --- Level 2 — Survival English ---
  {
    id: 'word-recommend',
    word: 'recommend',
    partOfSpeech: 'verb',
    definition: 'to suggest that someone or something is good or suitable for a particular purpose',
    pronunciation: '/ˌrɛkəˈmɛnd/',
    difficulty: 3,
    level: 2,
    topic: 'Restaurant',
  },
  {
    id: 'word-reservation',
    word: 'reservation',
    partOfSpeech: 'noun',
    definition: 'an arrangement to have a table, room, seat, etc. kept for you',
    pronunciation: '/ˌrɛzərˈveɪʃən/',
    difficulty: 4,
    level: 2,
    topic: 'Restaurant',
  },
  {
    id: 'word-available',
    word: 'available',
    partOfSpeech: 'adjective',
    definition: 'able to be used or obtained; free to do something',
    pronunciation: '/əˈveɪləbəl/',
    difficulty: 3,
    level: 2,
    topic: 'Restaurant',
  },
  {
    id: 'word-crowded',
    word: 'crowded',
    partOfSpeech: 'adjective',
    definition: 'full of people',
    pronunciation: '/ˈkraʊdɪd/',
    difficulty: 2,
    level: 2,
    topic: 'Restaurant',
  },
  {
    id: 'word-convenient',
    word: 'convenient',
    partOfSpeech: 'adjective',
    definition: 'suitable for your needs and plans; not causing problems',
    pronunciation: '/kənˈviːniənt/',
    difficulty: 4,
    level: 2,
    topic: 'Restaurant',
  },
  {
    id: 'word-checkin',
    word: 'check in',
    partOfSpeech: 'phrasal verb',
    definition: 'to arrive and register at a hotel, airport, etc.',
    pronunciation: '/tʃɛk ɪn/',
    difficulty: 3,
    level: 2,
    topic: 'Hotel',
  },
  {
    id: 'word-key',
    word: 'key',
    partOfSpeech: 'noun',
    definition: 'a card or object used to open a lock, such as a hotel room door',
    pronunciation: '/kiː/',
    difficulty: 1,
    level: 2,
    topic: 'Hotel',
  },
  {
    id: 'word-order',
    word: 'order',
    partOfSpeech: 'verb',
    definition: 'to ask for food, drink, or a product to be brought or sent to you',
    pronunciation: '/ˈɔːrdər/',
    difficulty: 2,
    level: 2,
    topic: 'Cafe',
  },
  {
    id: 'word-turn',
    word: 'turn',
    partOfSpeech: 'verb',
    definition: 'to change direction while moving',
    pronunciation: '/tɜːrn/',
    difficulty: 2,
    level: 2,
    topic: 'Directions',
  },
  {
    id: 'word-straight',
    word: 'straight',
    partOfSpeech: 'adverb',
    definition: 'continuing in one direction without turning',
    pronunciation: '/streɪt/',
    difficulty: 2,
    level: 2,
    topic: 'Directions',
  },
  {
    id: 'word-nearby',
    word: 'nearby',
    partOfSpeech: 'adjective',
    definition: 'not far away; close',
    pronunciation: '/ˌnɪrˈbaɪ/',
    difficulty: 2,
    level: 2,
    topic: 'Directions',
  },
  {
    id: 'word-ticket',
    word: 'ticket',
    partOfSpeech: 'noun',
    definition: 'a piece of paper or digital pass that shows you have paid to travel or enter somewhere',
    pronunciation: '/ˈtɪkɪt/',
    difficulty: 2,
    level: 2,
    topic: 'Transportation',
  },
  {
    id: 'word-platform',
    word: 'platform',
    partOfSpeech: 'noun',
    definition: 'the area in a station where you get on or off a train',
    pronunciation: '/ˈplætfɔːrm/',
    difficulty: 3,
    level: 2,
    topic: 'Transportation',
  },

  // --- Level 3 — Basic Conversation ---
  {
    id: 'word-family',
    word: 'family',
    partOfSpeech: 'noun',
    definition: 'a group of people related to each other, such as parents and children',
    pronunciation: '/ˈfæməli/',
    difficulty: 2,
    level: 3,
    topic: 'Family',
  },
  {
    id: 'word-brother',
    word: 'brother',
    partOfSpeech: 'noun',
    definition: 'a male sibling',
    pronunciation: '/ˈbrʌðər/',
    difficulty: 2,
    level: 3,
    topic: 'Family',
  },
  {
    id: 'word-job',
    word: 'job',
    partOfSpeech: 'noun',
    definition: 'the work someone does regularly to earn money',
    pronunciation: '/dʒɑːb/',
    difficulty: 2,
    level: 3,
    topic: 'Job',
  },
  {
    id: 'word-work',
    word: 'work',
    partOfSpeech: 'verb',
    definition: 'to do a job, often for a company or organization',
    pronunciation: '/wɜːrk/',
    difficulty: 2,
    level: 3,
    topic: 'Job',
  },
  {
    id: 'word-hobby',
    word: 'hobby',
    partOfSpeech: 'noun',
    definition: 'an activity you do regularly for enjoyment in your free time',
    pronunciation: '/ˈhɑːbi/',
    difficulty: 2,
    level: 3,
    topic: 'Hobbies',
  },
  {
    id: 'word-favorite',
    word: 'favorite',
    partOfSpeech: 'adjective',
    definition: 'liked more than any other of the same kind',
    pronunciation: '/ˈfeɪvərɪt/',
    difficulty: 2,
    level: 3,
    topic: 'Preferences',
  },
  {
    id: 'word-prefer',
    word: 'prefer',
    partOfSpeech: 'verb',
    definition: 'to like one thing more than another',
    pronunciation: '/prɪˈfɜːr/',
    difficulty: 3,
    level: 3,
    topic: 'Preferences',
  },
  {
    id: 'word-usually',
    word: 'usually',
    partOfSpeech: 'adverb',
    definition: 'most of the time; more often than not',
    pronunciation: '/ˈjuːʒuəli/',
    difficulty: 3,
    level: 3,
    topic: 'Daily Routine',
  },
  {
    id: 'word-wake-up',
    word: 'wake up',
    partOfSpeech: 'phrasal verb',
    definition: 'to stop sleeping and become conscious',
    pronunciation: '/weɪk ʌp/',
    difficulty: 2,
    level: 3,
    topic: 'Daily Routine',
  },
  {
    id: 'word-weather',
    word: 'weather',
    partOfSpeech: 'noun',
    definition: 'the condition of the atmosphere, e.g. sunny, rainy, or cold',
    pronunciation: '/ˈweðər/',
    difficulty: 2,
    level: 3,
    topic: 'Weather',
  },
  {
    id: 'word-rain',
    word: 'rain',
    partOfSpeech: 'verb',
    definition: 'when water falls from the clouds',
    pronunciation: '/reɪn/',
    difficulty: 2,
    level: 3,
    topic: 'Weather',
  },
  {
    id: 'word-appointment',
    word: 'appointment',
    partOfSpeech: 'noun',
    definition: 'an arrangement to meet someone or be somewhere at a fixed time',
    pronunciation: '/əˈpɔɪntmənt/',
    difficulty: 3,
    level: 3,
    topic: 'Appointments',
  },
  {
    id: 'word-schedule',
    word: 'schedule',
    partOfSpeech: 'noun',
    definition: 'a plan of things to do and when to do them',
    pronunciation: '/ˈskedʒuːl/',
    difficulty: 3,
    level: 3,
    topic: 'Appointments',
  },

  // --- Level 4 — Everyday Life ---
  {
    id: 'word-friend',
    word: 'friend',
    partOfSpeech: 'noun',
    definition: 'a person you know well and like',
    pronunciation: '/frend/',
    difficulty: 2,
    level: 4,
    topic: 'Friends',
  },
  {
    id: 'word-invite',
    word: 'invite',
    partOfSpeech: 'verb',
    definition: 'to ask someone to come to an event or place',
    pronunciation: '/ɪnˈvaɪt/',
    difficulty: 3,
    level: 4,
    topic: 'Invitations',
  },
  {
    id: 'word-party',
    word: 'party',
    partOfSpeech: 'noun',
    definition: 'a social event where people meet to celebrate or enjoy themselves',
    pronunciation: '/ˈpɑːrti/',
    difficulty: 2,
    level: 4,
    topic: 'Invitations',
  },
  {
    id: 'word-ask',
    word: 'ask',
    partOfSpeech: 'verb',
    definition: 'to say something in order to get information or make a request',
    pronunciation: '/æsk/',
    difficulty: 2,
    level: 4,
    topic: 'Requests',
  },
  {
    id: 'word-favor',
    word: 'favor',
    partOfSpeech: 'noun',
    definition: 'a kind or helpful act you ask of or do for someone',
    pronunciation: '/ˈfeɪvər/',
    difficulty: 3,
    level: 4,
    topic: 'Requests',
  },
  {
    id: 'word-apologize',
    word: 'apologize',
    partOfSpeech: 'verb',
    definition: 'to say sorry for something you did wrong',
    pronunciation: '/əˈpɑːlədʒaɪz/',
    difficulty: 3,
    level: 4,
    topic: 'Apologies',
  },
  {
    id: 'word-mistake',
    word: 'mistake',
    partOfSpeech: 'noun',
    definition: 'something done incorrectly, by accident or lack of knowledge',
    pronunciation: '/mɪˈsteɪk/',
    difficulty: 3,
    level: 4,
    topic: 'Apologies',
  },
  {
    id: 'word-feel',
    word: 'feel',
    partOfSpeech: 'verb',
    definition: 'to experience a physical or emotional state',
    pronunciation: '/fiːl/',
    difficulty: 2,
    level: 4,
    topic: 'Feelings',
  },
  {
    id: 'word-excited',
    word: 'excited',
    partOfSpeech: 'adjective',
    definition: 'feeling very happy and enthusiastic about something',
    pronunciation: '/ɪkˈsaɪtɪd/',
    difficulty: 3,
    level: 4,
    topic: 'Feelings',
  },
  {
    id: 'word-weekend',
    word: 'weekend',
    partOfSpeech: 'noun',
    definition: 'Saturday and Sunday',
    pronunciation: '/ˈwiːkend/',
    difficulty: 2,
    level: 4,
    topic: 'Weekends',
  },
  {
    id: 'word-relax',
    word: 'relax',
    partOfSpeech: 'verb',
    definition: 'to rest and stop worrying or working',
    pronunciation: '/rɪˈlæks/',
    difficulty: 3,
    level: 4,
    topic: 'Weekends',
  },
  {
    id: 'word-experience',
    word: 'experience',
    partOfSpeech: 'noun',
    definition: 'something that happens to you that affects how you feel or what you know',
    pronunciation: '/ɪkˈspɪriəns/',
    difficulty: 4,
    level: 4,
    topic: 'Personal Experiences',
  },
  {
    id: 'word-happen',
    word: 'happen',
    partOfSpeech: 'verb',
    definition: 'to take place; to occur',
    pronunciation: '/ˈhæpən/',
    difficulty: 2,
    level: 4,
    topic: 'Personal Experiences',
  },

  // --- Level 5 — Social Conversation ---
  {
    id: 'word-interesting',
    word: 'interesting',
    partOfSpeech: 'adjective',
    definition: 'attracting attention or curiosity',
    pronunciation: '/ˈɪntrəstɪŋ/',
    difficulty: 3,
    level: 5,
    topic: 'Interests',
  },
  {
    id: 'word-curious',
    word: 'curious',
    partOfSpeech: 'adjective',
    definition: 'eager to know or learn something',
    pronunciation: '/ˈkjʊriəs/',
    difficulty: 3,
    level: 5,
    topic: 'Interests',
  },
  {
    id: 'word-tradition',
    word: 'tradition',
    partOfSpeech: 'noun',
    definition: 'a custom or belief passed down through generations',
    pronunciation: '/trəˈdɪʃən/',
    difficulty: 4,
    level: 5,
    topic: 'Culture',
  },
  {
    id: 'word-custom',
    word: 'custom',
    partOfSpeech: 'noun',
    definition: 'a usual way of behaving or doing things in a place or culture',
    pronunciation: '/ˈkʌstəm/',
    difficulty: 4,
    level: 5,
    topic: 'Culture',
  },
  {
    id: 'word-genre',
    word: 'genre',
    partOfSpeech: 'noun',
    definition: 'a category of art, music, or writing with a particular style',
    pronunciation: '/ˈʒɑːnrə/',
    difficulty: 4,
    level: 5,
    topic: 'Movies & Music',
  },
  {
    id: 'word-actor',
    word: 'actor',
    partOfSpeech: 'noun',
    definition: 'a person who performs in films, TV shows, or plays',
    pronunciation: '/ˈæktər/',
    difficulty: 2,
    level: 5,
    topic: 'Movies & Music',
  },
  {
    id: 'word-song',
    word: 'song',
    partOfSpeech: 'noun',
    definition: 'a short piece of music with words that is sung',
    pronunciation: '/sɔːŋ/',
    difficulty: 1,
    level: 5,
    topic: 'Movies & Music',
  },
  {
    id: 'word-delicious',
    word: 'delicious',
    partOfSpeech: 'adjective',
    definition: 'having a very pleasant taste',
    pronunciation: '/dɪˈlɪʃəs/',
    difficulty: 3,
    level: 5,
    topic: 'Food',
  },
  {
    id: 'word-spicy',
    word: 'spicy',
    partOfSpeech: 'adjective',
    definition: 'having a strong, hot flavor',
    pronunciation: '/ˈspaɪsi/',
    difficulty: 2,
    level: 5,
    topic: 'Food',
  },
  {
    id: 'word-abroad',
    word: 'abroad',
    partOfSpeech: 'adverb',
    definition: 'in or to a foreign country',
    pronunciation: '/əˈbrɔːd/',
    difficulty: 3,
    level: 5,
    topic: 'Travel Experiences',
  },
  {
    id: 'word-memorable',
    word: 'memorable',
    partOfSpeech: 'adjective',
    definition: 'worth remembering; not easily forgotten',
    pronunciation: '/ˈmemərəbəl/',
    difficulty: 4,
    level: 5,
    topic: 'Travel Experiences',
  },
  {
    id: 'word-agree',
    word: 'agree',
    partOfSpeech: 'verb',
    definition: 'to have the same opinion as someone else',
    pronunciation: '/əˈɡriː/',
    difficulty: 2,
    level: 5,
    topic: 'Maintaining Conversation',
  },
  {
    id: 'word-by-the-way',
    word: 'by the way',
    partOfSpeech: 'phrase',
    definition: 'used to introduce a new, often unrelated, topic into a conversation',
    pronunciation: '/baɪ ðə weɪ/',
    difficulty: 2,
    level: 5,
    topic: 'Maintaining Conversation',
  },

  // --- Level 6 — Core Vocabulary (frequency-based) ---
  // Breadth-focused batch 1: common everyday words selected from a
  // real English word-frequency list, not tied to one conversation topic.
  // Lighter per-word depth than Levels 1-5 (2 phrases, no dedicated
  // dialogue) is deliberate — a memorization-first app needs word count
  // more than it needs a roleplay for every single word (spec 2.1: word,
  // listening, and speaking learning are linked, but that does not mean
  // every word needs a full roleplay). More batches will follow toward
  // much broader coverage.
  {
    id: 'word-home',
    word: 'home',
    partOfSpeech: 'noun',
    definition: 'the place where you live',
    pronunciation: '/hoʊm/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-people',
    word: 'people',
    partOfSpeech: 'noun',
    definition: 'men, women, and children in general',
    pronunciation: '/ˈpiːpəl/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-year',
    word: 'year',
    partOfSpeech: 'noun',
    definition: 'a period of twelve months',
    pronunciation: '/jɪr/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-health',
    word: 'health',
    partOfSpeech: 'noun',
    definition: 'the state of being physically and mentally well',
    pronunciation: '/helθ/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-world',
    word: 'world',
    partOfSpeech: 'noun',
    definition: 'the earth and all the people and things on it',
    pronunciation: '/wɜːrld/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-buy',
    word: 'buy',
    partOfSpeech: 'verb',
    definition: 'to get something by paying money for it',
    pronunciation: '/baɪ/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-make',
    word: 'make',
    partOfSpeech: 'verb',
    definition: 'to create or produce something',
    pronunciation: '/meɪk/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-product',
    word: 'product',
    partOfSpeech: 'noun',
    definition: 'something that is made to be sold',
    pronunciation: '/ˈprɑːdʌkt/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-system',
    word: 'system',
    partOfSpeech: 'noun',
    definition: 'a set of things working together as a whole',
    pronunciation: '/ˈsɪstəm/',
    difficulty: 3,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-city',
    word: 'city',
    partOfSpeech: 'noun',
    definition: 'a large town',
    pronunciation: '/ˈsɪti/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-message',
    word: 'message',
    partOfSpeech: 'noun',
    definition: 'a short piece of information sent to someone',
    pronunciation: '/ˈmesɪdʒ/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-good',
    word: 'good',
    partOfSpeech: 'adjective',
    definition: 'of high quality or a positive kind',
    pronunciation: '/ɡʊd/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-video',
    word: 'video',
    partOfSpeech: 'noun',
    definition: 'a recording of moving images',
    pronunciation: '/ˈvɪdioʊ/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-well',
    word: 'well',
    partOfSpeech: 'adverb',
    definition: 'in a good or satisfactory way',
    pronunciation: '/wel/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-public',
    word: 'public',
    partOfSpeech: 'adjective',
    definition: 'open to or shared by everyone',
    pronunciation: '/ˈpʌblɪk/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-high',
    word: 'high',
    partOfSpeech: 'adjective',
    definition: 'measuring a great distance from top to bottom',
    pronunciation: '/haɪ/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-school',
    word: 'school',
    partOfSpeech: 'noun',
    definition: 'a place where children go to learn',
    pronunciation: '/skuːl/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-book',
    word: 'book',
    partOfSpeech: 'noun',
    definition: 'a set of printed pages fixed together in a cover',
    pronunciation: '/bʊk/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-company',
    word: 'company',
    partOfSpeech: 'noun',
    definition: 'a business that makes or sells things',
    pronunciation: '/ˈkʌmpəni/',
    difficulty: 3,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-read',
    word: 'read',
    partOfSpeech: 'verb',
    definition: 'to look at and understand written words',
    pronunciation: '/riːd/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-group',
    word: 'group',
    partOfSpeech: 'noun',
    definition: 'a number of people or things together',
    pronunciation: '/ɡruːp/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-need',
    word: 'need',
    partOfSpeech: 'verb',
    definition: 'to require something because it is necessary',
    pronunciation: '/niːd/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-life',
    word: 'life',
    partOfSpeech: 'noun',
    definition: 'the period between birth and death',
    pronunciation: '/laɪf/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-way',
    word: 'way',
    partOfSpeech: 'noun',
    definition: 'a method or manner of doing something',
    pronunciation: '/weɪ/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-day',
    word: 'day',
    partOfSpeech: 'noun',
    definition: 'a period of twenty-four hours',
    pronunciation: '/deɪ/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-great',
    word: 'great',
    partOfSpeech: 'adjective',
    definition: 'very good; excellent',
    pronunciation: '/ɡreɪt/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-real',
    word: 'real',
    partOfSpeech: 'adjective',
    definition: 'actually existing, not imagined',
    pronunciation: '/riːl/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-store',
    word: 'store',
    partOfSpeech: 'noun',
    definition: 'a shop',
    pronunciation: '/stɔːr/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-line',
    word: 'line',
    partOfSpeech: 'noun',
    definition: 'a long thin mark, or a row of people',
    pronunciation: '/laɪn/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-type',
    word: 'type',
    partOfSpeech: 'noun',
    definition: 'a category of things with shared features',
    pronunciation: '/taɪp/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-car',
    word: 'car',
    partOfSpeech: 'noun',
    definition: 'a road vehicle with an engine',
    pronunciation: '/kɑːr/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-design',
    word: 'design',
    partOfSpeech: 'verb',
    definition: 'to plan and create something for a purpose',
    pronunciation: '/dɪˈzaɪn/',
    difficulty: 3,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-address',
    word: 'address',
    partOfSpeech: 'noun',
    definition: 'the details of where someone lives',
    pronunciation: '/əˈdres/',
    difficulty: 3,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-area',
    word: 'area',
    partOfSpeech: 'noun',
    definition: 'a particular part of a place',
    pronunciation: '/ˈeriə/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-want',
    word: 'want',
    partOfSpeech: 'verb',
    definition: 'to have a desire for something',
    pronunciation: '/wɑːnt/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-phone',
    word: 'phone',
    partOfSpeech: 'noun',
    definition: 'a device used to talk to someone far away',
    pronunciation: '/foʊn/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-long',
    word: 'long',
    partOfSpeech: 'adjective',
    definition: 'measuring a great distance or time',
    pronunciation: '/lɔːŋ/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-change',
    word: 'change',
    partOfSpeech: 'verb',
    definition: 'to make or become different',
    pronunciation: '/tʃeɪndʒ/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-small',
    word: 'small',
    partOfSpeech: 'adjective',
    definition: 'little in size',
    pronunciation: '/smɔːl/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-sign',
    word: 'sign',
    partOfSpeech: 'noun',
    definition: 'a board or symbol that gives information',
    pronunciation: '/saɪn/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-open',
    word: 'open',
    partOfSpeech: 'adjective',
    definition: 'allowing people to enter; not closed',
    pronunciation: '/ˈoʊpən/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-case',
    word: 'case',
    partOfSpeech: 'noun',
    definition: 'a particular situation or instance',
    pronunciation: '/keɪs/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-same',
    word: 'same',
    partOfSpeech: 'adjective',
    definition: 'identical; not different',
    pronunciation: '/seɪm/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-own',
    word: 'own',
    partOfSpeech: 'adjective',
    definition: 'belonging to oneself',
    pronunciation: '/oʊn/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-find',
    word: 'find',
    partOfSpeech: 'verb',
    definition: 'to discover or locate something',
    pronunciation: '/faɪnd/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-house',
    word: 'house',
    partOfSpeech: 'noun',
    definition: 'a building where people live',
    pronunciation: '/haʊs/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-power',
    word: 'power',
    partOfSpeech: 'noun',
    definition: 'the ability to control or influence; electricity',
    pronunciation: '/ˈpaʊər/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-water',
    word: 'water',
    partOfSpeech: 'noun',
    definition: 'a clear liquid needed for life',
    pronunciation: '/ˈwɔːtər/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-history',
    word: 'history',
    partOfSpeech: 'noun',
    definition: 'the study of past events',
    pronunciation: '/ˈhɪstəri/',
    difficulty: 3,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-size',
    word: 'size',
    partOfSpeech: 'noun',
    definition: 'how big or small something is',
    pronunciation: '/saɪz/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-personal',
    word: 'personal',
    partOfSpeech: 'adjective',
    definition: 'private; relating to one particular person',
    pronunciation: '/ˈpɜːrsənəl/',
    difficulty: 3,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-shop',
    word: 'shop',
    partOfSpeech: 'verb',
    definition: 'to go and buy things',
    pronunciation: '/ʃɑːp/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-white',
    word: 'white',
    partOfSpeech: 'adjective',
    definition: 'having the color of snow or milk',
    pronunciation: '/waɪt/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-text',
    word: 'text',
    partOfSpeech: 'verb',
    definition: 'to send a written message by phone',
    pronunciation: '/tekst/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-government',
    word: 'government',
    partOfSpeech: 'noun',
    definition: 'the group that officially governs a country',
    pronunciation: '/ˈɡʌvərnmənt/',
    difficulty: 4,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-children',
    word: 'children',
    partOfSpeech: 'noun',
    definition: 'young people; the plural of child',
    pronunciation: '/ˈtʃɪldrən/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-return',
    word: 'return',
    partOfSpeech: 'verb',
    definition: 'to come or go back; to give something back',
    pronunciation: '/rɪˈtɜːrn/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-level',
    word: 'level',
    partOfSpeech: 'noun',
    definition: 'a position on a scale of amount or quality',
    pronunciation: '/ˈlevəl/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-love',
    word: 'love',
    partOfSpeech: 'verb',
    definition: 'to like someone or something very much',
    pronunciation: '/lʌv/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-call',
    word: 'call',
    partOfSpeech: 'verb',
    definition: 'to speak to someone by phone',
    pronunciation: '/kɔːl/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-hour',
    word: 'hour',
    partOfSpeech: 'noun',
    definition: 'a period of sixty minutes',
    pronunciation: '/aʊər/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-image',
    word: 'image',
    partOfSpeech: 'noun',
    definition: 'a picture or visual representation',
    pronunciation: '/ˈɪmɪdʒ/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-another',
    word: 'another',
    partOfSpeech: 'adjective',
    definition: 'one more; a different one',
    pronunciation: '/əˈnʌðər/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-money',
    word: 'money',
    partOfSpeech: 'noun',
    definition: 'coins and banknotes used to pay for things',
    pronunciation: '/ˈmʌni/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-quality',
    word: 'quality',
    partOfSpeech: 'noun',
    definition: 'how good or bad something is',
    pronunciation: '/ˈkwɑːləti/',
    difficulty: 3,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-value',
    word: 'value',
    partOfSpeech: 'noun',
    definition: 'how useful or important something is; worth',
    pronunciation: '/ˈvæljuː/',
    difficulty: 3,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-man',
    word: 'man',
    partOfSpeech: 'noun',
    definition: 'an adult male person',
    pronunciation: '/mæn/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-provide',
    word: 'provide',
    partOfSpeech: 'verb',
    definition: 'to give someone something they need',
    pronunciation: '/prəˈvaɪd/',
    difficulty: 3,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-food',
    word: 'food',
    partOfSpeech: 'noun',
    definition: 'things people and animals eat',
    pronunciation: '/fuːd/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-different',
    word: 'different',
    partOfSpeech: 'adjective',
    definition: 'not the same as another',
    pronunciation: '/ˈdɪfərənt/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-learn',
    word: 'learn',
    partOfSpeech: 'verb',
    definition: 'to gain knowledge or a skill',
    pronunciation: '/lɜːrn/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-course',
    word: 'course',
    partOfSpeech: 'noun',
    definition: 'a series of lessons on a subject',
    pronunciation: '/kɔːrs/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-room',
    word: 'room',
    partOfSpeech: 'noun',
    definition: 'a separate area inside a building',
    pronunciation: '/ruːm/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-point',
    word: 'point',
    partOfSpeech: 'noun',
    definition: 'an idea or opinion someone expresses; a place',
    pronunciation: '/pɔɪnt/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-join',
    word: 'join',
    partOfSpeech: 'verb',
    definition: 'to become a member of, or to come together with',
    pronunciation: '/dʒɔɪn/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-science',
    word: 'science',
    partOfSpeech: 'noun',
    definition: 'the study of the physical world through experiments',
    pronunciation: '/ˈsaɪəns/',
    difficulty: 2,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-team',
    word: 'team',
    partOfSpeech: 'noun',
    definition: 'a group of people working together',
    pronunciation: '/tiːm/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-week',
    word: 'week',
    partOfSpeech: 'noun',
    definition: 'a period of seven days',
    pronunciation: '/wiːk/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
  {
    id: 'word-plan',
    word: 'plan',
    partOfSpeech: 'noun',
    definition: 'a set of decisions about how to do something',
    pronunciation: '/plæn/',
    difficulty: 1,
    level: 6,
    topic: 'Core Vocabulary',
  },
];

export function vocabularyById(id: string): VocabularyItem | undefined {
  return vocabulary.find((v) => v.id === id);
}

export function vocabularyByLevel(level: number): VocabularyItem[] {
  return vocabulary.filter((v) => v.level === level);
}

// spec 7 — the same word is heard across many contexts, never just once.
export const phrases: Phrase[] = [
  // --- Level 1 ---
  // hello
  { id: 'phrase-hello-greetings', vocabularyItemId: 'word-hello', text: 'Hello! How are you?', meaning: '안녕하세요! 어떻게 지내세요?', contextId: 'ctx-greetings', difficulty: 'easy' },
  { id: 'phrase-hello-introductions', vocabularyItemId: 'word-hello', text: "Hello, I'm Claude.", meaning: '안녕하세요, 저는 클로드입니다.', contextId: 'ctx-introductions', difficulty: 'easy' },
  { id: 'phrase-hello-casual', vocabularyItemId: 'word-hello', text: 'Hello? Is anyone there?', meaning: '여보세요? 거기 누구 계세요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // goodbye
  { id: 'phrase-goodbye-greetings', vocabularyItemId: 'word-goodbye', text: 'Goodbye, see you tomorrow!', meaning: '안녕히 가세요, 내일 봐요!', contextId: 'ctx-greetings', difficulty: 'easy' },
  { id: 'phrase-goodbye-introductions', vocabularyItemId: 'word-goodbye', text: 'It was nice meeting you, goodbye!', meaning: '만나서 반가웠어요, 안녕히 가세요!', contextId: 'ctx-introductions', difficulty: 'medium' },
  { id: 'phrase-goodbye-casual', vocabularyItemId: 'word-goodbye', text: 'I have to say goodbye now.', meaning: '이제 작별 인사를 해야겠어요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // name
  { id: 'phrase-name-introductions', vocabularyItemId: 'word-name', text: "What's your name?", meaning: '이름이 뭐예요?', contextId: 'ctx-introductions', difficulty: 'easy' },
  { id: 'phrase-name-courtesy', vocabularyItemId: 'word-name', text: 'Could I have your name, please?', meaning: '성함을 알려주시겠어요?', contextId: 'ctx-courtesy', difficulty: 'medium' },
  { id: 'phrase-name-casual', vocabularyItemId: 'word-name', text: 'I forgot his name.', meaning: '그의 이름을 잊어버렸어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // meet
  { id: 'phrase-meet-introductions', vocabularyItemId: 'word-meet', text: 'Nice to meet you.', meaning: '만나서 반가워요.', contextId: 'ctx-introductions', difficulty: 'easy' },
  { id: 'phrase-meet-time', vocabularyItemId: 'word-meet', text: 'When can we meet?', meaning: '언제 만날 수 있을까요?', contextId: 'ctx-time', difficulty: 'easy' },
  { id: 'phrase-meet-casual', vocabularyItemId: 'word-meet', text: "Let's meet at 5pm.", meaning: '5시에 만나요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // from
  { id: 'phrase-from-introductions', vocabularyItemId: 'word-from', text: 'Where are you from?', meaning: '어디서 오셨어요?', contextId: 'ctx-introductions', difficulty: 'easy' },
  { id: 'phrase-from-courtesy', vocabularyItemId: 'word-from', text: "I'm calling from the front desk.", meaning: '프런트 데스크에서 전화드립니다.', contextId: 'ctx-courtesy', difficulty: 'medium' },
  { id: 'phrase-from-casual', vocabularyItemId: 'word-from', text: 'This gift is from my friend.', meaning: '이 선물은 제 친구가 준 거예요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // live
  { id: 'phrase-live-introductions', vocabularyItemId: 'word-live', text: 'Where do you live?', meaning: '어디 사세요?', contextId: 'ctx-introductions', difficulty: 'easy' },
  { id: 'phrase-live-courtesy', vocabularyItemId: 'word-live', text: 'Do you live alone?', meaning: '혼자 사세요?', contextId: 'ctx-courtesy', difficulty: 'easy' },
  { id: 'phrase-live-casual', vocabularyItemId: 'word-live', text: 'I live near here.', meaning: '저는 이 근처에 살아요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // old
  { id: 'phrase-old-introductions', vocabularyItemId: 'word-old', text: 'How old are you?', meaning: '몇 살이에요?', contextId: 'ctx-introductions', difficulty: 'easy' },
  { id: 'phrase-old-numbers', vocabularyItemId: 'word-old', text: "I'm twenty years old.", meaning: '저는 스무 살이에요.', contextId: 'ctx-numbers', difficulty: 'easy' },
  { id: 'phrase-old-casual', vocabularyItemId: 'word-old', text: 'This building is very old.', meaning: '이 건물은 매우 오래됐어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // please
  { id: 'phrase-please-courtesy', vocabularyItemId: 'word-please', text: 'Please sit down.', meaning: '앉아 주세요.', contextId: 'ctx-courtesy', difficulty: 'easy' },
  { id: 'phrase-please-numbers', vocabularyItemId: 'word-please', text: 'Two coffees, please.', meaning: '커피 두 잔 주세요.', contextId: 'ctx-numbers', difficulty: 'easy' },
  { id: 'phrase-please-casual', vocabularyItemId: 'word-please', text: 'Can you help me, please?', meaning: '도와주시겠어요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // thank you
  { id: 'phrase-thankyou-courtesy', vocabularyItemId: 'word-thank-you', text: 'Thank you very much.', meaning: '정말 감사합니다.', contextId: 'ctx-courtesy', difficulty: 'easy' },
  { id: 'phrase-thankyou-introductions', vocabularyItemId: 'word-thank-you', text: 'Thank you, nice to meet you too.', meaning: '감사합니다, 저도 만나서 반가워요.', contextId: 'ctx-introductions', difficulty: 'medium' },
  { id: 'phrase-thankyou-casual', vocabularyItemId: 'word-thank-you', text: 'Thank you for coming.', meaning: '와주셔서 감사합니다.', contextId: 'ctx-casual', difficulty: 'easy' },

  // sorry
  { id: 'phrase-sorry-courtesy', vocabularyItemId: 'word-sorry', text: "I'm sorry for being late.", meaning: '늦어서 죄송합니다.', contextId: 'ctx-courtesy', difficulty: 'easy' },
  { id: 'phrase-sorry-introductions', vocabularyItemId: 'word-sorry', text: "Sorry, I didn't catch your name.", meaning: '죄송한데 성함을 못 들었어요.', contextId: 'ctx-introductions', difficulty: 'medium' },
  { id: 'phrase-sorry-casual', vocabularyItemId: 'word-sorry', text: 'Sorry, can you repeat that?', meaning: '죄송한데 다시 말씀해 주시겠어요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // today
  { id: 'phrase-today-time', vocabularyItemId: 'word-today', text: "What's the date today?", meaning: '오늘 며칠이에요?', contextId: 'ctx-time', difficulty: 'easy' },
  { id: 'phrase-today-courtesy', vocabularyItemId: 'word-today', text: 'Is the office open today?', meaning: '오늘 사무실 문 열어요?', contextId: 'ctx-courtesy', difficulty: 'easy' },
  { id: 'phrase-today-casual', vocabularyItemId: 'word-today', text: 'I feel great today.', meaning: '오늘 기분이 아주 좋아요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // tomorrow
  { id: 'phrase-tomorrow-time', vocabularyItemId: 'word-tomorrow', text: 'See you tomorrow.', meaning: '내일 봐요.', contextId: 'ctx-time', difficulty: 'easy' },
  { id: 'phrase-tomorrow-courtesy', vocabularyItemId: 'word-tomorrow', text: 'Can we meet tomorrow instead?', meaning: '대신 내일 만날 수 있을까요?', contextId: 'ctx-courtesy', difficulty: 'easy' },
  { id: 'phrase-tomorrow-casual', vocabularyItemId: 'word-tomorrow', text: "I'm busy tomorrow.", meaning: '저는 내일 바빠요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // number
  { id: 'phrase-number-numbers', vocabularyItemId: 'word-number', text: "What's your phone number?", meaning: '전화번호가 어떻게 되세요?', contextId: 'ctx-numbers', difficulty: 'easy' },
  { id: 'phrase-number-courtesy', vocabularyItemId: 'word-number', text: 'Could you give me your number?', meaning: '번호를 알려주시겠어요?', contextId: 'ctx-courtesy', difficulty: 'medium' },
  { id: 'phrase-number-casual', vocabularyItemId: 'word-number', text: 'I forgot the number.', meaning: '번호를 잊어버렸어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // --- Level 2 ---
  // recommend
  { id: 'phrase-recommend-restaurant', vocabularyItemId: 'word-recommend', text: 'What do you recommend?', meaning: '무엇을 추천하시나요?', contextId: 'ctx-restaurant', difficulty: 'easy' },
  { id: 'phrase-recommend-travel', vocabularyItemId: 'word-recommend', text: 'Can you recommend a good hotel?', meaning: '좋은 호텔 좀 추천해 주시겠어요?', contextId: 'ctx-travel', difficulty: 'medium' },
  { id: 'phrase-recommend-movie', vocabularyItemId: 'word-recommend', text: 'Would you recommend this movie?', meaning: '이 영화 추천하시나요?', contextId: 'ctx-movie', difficulty: 'easy' },
  { id: 'phrase-recommend-shopping', vocabularyItemId: 'word-recommend', text: 'Can you recommend something for a gift?', meaning: '선물할 만한 걸 추천해 주시겠어요?', contextId: 'ctx-shopping', difficulty: 'medium' },
  { id: 'phrase-recommend-casual', vocabularyItemId: 'word-recommend', text: 'What would you recommend?', meaning: '뭘 추천하시겠어요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // reservation
  { id: 'phrase-reservation-restaurant', vocabularyItemId: 'word-reservation', text: "I'd like to make a reservation.", meaning: '예약을 하고 싶습니다.', contextId: 'ctx-restaurant', difficulty: 'medium' },
  { id: 'phrase-reservation-hotel', vocabularyItemId: 'word-reservation', text: 'I have a reservation under Kim.', meaning: 'Kim으로 예약했습니다.', contextId: 'ctx-hotel', difficulty: 'medium' },
  { id: 'phrase-reservation-travel', vocabularyItemId: 'word-reservation', text: 'Do I need a reservation to visit?', meaning: '방문하려면 예약이 필요한가요?', contextId: 'ctx-travel', difficulty: 'medium' },

  // available
  { id: 'phrase-available-restaurant', vocabularyItemId: 'word-available', text: 'Is a table available at 7pm?', meaning: '7시에 자리가 있나요?', contextId: 'ctx-restaurant', difficulty: 'medium' },
  { id: 'phrase-available-hotel', vocabularyItemId: 'word-available', text: 'Do you have any rooms available tonight?', meaning: '오늘 밤 이용 가능한 방이 있나요?', contextId: 'ctx-hotel', difficulty: 'medium' },
  { id: 'phrase-available-shopping', vocabularyItemId: 'word-available', text: 'Is this available in a different color?', meaning: '이거 다른 색상으로 있나요?', contextId: 'ctx-shopping', difficulty: 'medium' },

  // crowded
  { id: 'phrase-crowded-restaurant', vocabularyItemId: 'word-crowded', text: 'This place looks really crowded tonight.', meaning: '오늘 밤 여기 정말 붐비네요.', contextId: 'ctx-restaurant', difficulty: 'medium' },
  { id: 'phrase-crowded-transportation', vocabularyItemId: 'word-crowded', text: 'The train is really crowded during rush hour.', meaning: '출퇴근 시간에는 기차가 정말 붐벼요.', contextId: 'ctx-transportation', difficulty: 'medium' },
  { id: 'phrase-crowded-travel', vocabularyItemId: 'word-crowded', text: 'This area gets crowded in summer.', meaning: '여름엔 이 지역이 붐벼요.', contextId: 'ctx-travel', difficulty: 'medium' },

  // convenient
  { id: 'phrase-convenient-restaurant', vocabularyItemId: 'word-convenient', text: 'Is 7pm a convenient time for you?', meaning: '7시가 편하신가요?', contextId: 'ctx-restaurant', difficulty: 'medium' },
  { id: 'phrase-convenient-hotel', vocabularyItemId: 'word-convenient', text: 'The hotel location is very convenient.', meaning: '호텔 위치가 아주 편리해요.', contextId: 'ctx-hotel', difficulty: 'medium' },
  { id: 'phrase-convenient-casual', vocabularyItemId: 'word-convenient', text: 'Would tomorrow be more convenient?', meaning: '내일이 더 편하실까요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // check in
  { id: 'phrase-checkin-hotel', vocabularyItemId: 'word-checkin', text: "I'd like to check in, please.", meaning: '체크인하고 싶습니다.', contextId: 'ctx-hotel', difficulty: 'medium' },
  { id: 'phrase-checkin-travel', vocabularyItemId: 'word-checkin', text: 'What time can I check in?', meaning: '몇 시에 체크인할 수 있나요?', contextId: 'ctx-travel', difficulty: 'medium' },
  { id: 'phrase-checkin-casual', vocabularyItemId: 'word-checkin', text: 'Have you checked in yet?', meaning: '너 체크인 했어?', contextId: 'ctx-casual', difficulty: 'easy' },

  // key
  { id: 'phrase-key-hotel', vocabularyItemId: 'word-key', text: 'Can I get an extra key?', meaning: '여분의 키를 받을 수 있을까요?', contextId: 'ctx-hotel', difficulty: 'medium' },
  { id: 'phrase-key-casual', vocabularyItemId: 'word-key', text: 'I think I left my key inside.', meaning: '안에 키를 두고 온 것 같아요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-key-travel', vocabularyItemId: 'word-key', text: 'Where do I return the key?', meaning: '키는 어디에 반납하나요?', contextId: 'ctx-travel', difficulty: 'medium' },

  // order
  { id: 'phrase-order-cafe', vocabularyItemId: 'word-order', text: "I'd like to order a coffee.", meaning: '커피 주문하고 싶어요.', contextId: 'ctx-cafe', difficulty: 'medium' },
  { id: 'phrase-order-restaurant', vocabularyItemId: 'word-order', text: 'Are you ready to order?', meaning: '주문하시겠어요?', contextId: 'ctx-restaurant', difficulty: 'easy' },
  { id: 'phrase-order-shopping', vocabularyItemId: 'word-order', text: 'Can I order this online?', meaning: '이거 온라인으로 주문할 수 있나요?', contextId: 'ctx-shopping', difficulty: 'easy' },

  // turn
  { id: 'phrase-turn-directions', vocabularyItemId: 'word-turn', text: 'Turn left at the corner.', meaning: '모퉁이에서 좌회전하세요.', contextId: 'ctx-directions', difficulty: 'easy' },
  { id: 'phrase-turn-travel', vocabularyItemId: 'word-turn', text: 'Which way do I turn for the station?', meaning: '역으로 가려면 어느 쪽으로 도나요?', contextId: 'ctx-travel', difficulty: 'medium' },
  { id: 'phrase-turn-casual', vocabularyItemId: 'word-turn', text: "It's your turn to choose.", meaning: '네가 고를 차례야.', contextId: 'ctx-casual', difficulty: 'easy' },

  // straight
  { id: 'phrase-straight-directions', vocabularyItemId: 'word-straight', text: 'Go straight for two blocks.', meaning: '두 블록 직진하세요.', contextId: 'ctx-directions', difficulty: 'easy' },
  { id: 'phrase-straight-travel', vocabularyItemId: 'word-straight', text: 'Just walk straight from the exit.', meaning: '출구에서 그냥 직진해서 걸으세요.', contextId: 'ctx-travel', difficulty: 'medium' },
  { id: 'phrase-straight-casual', vocabularyItemId: 'word-straight', text: "Just go straight ahead, you can't miss it.", meaning: '그냥 쭉 직진하면 바로 보여요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // nearby
  { id: 'phrase-nearby-directions', vocabularyItemId: 'word-nearby', text: 'Is there a pharmacy nearby?', meaning: '근처에 약국이 있나요?', contextId: 'ctx-directions', difficulty: 'easy' },
  { id: 'phrase-nearby-travel', vocabularyItemId: 'word-nearby', text: 'Is the hotel nearby the station?', meaning: '호텔이 역 근처에 있나요?', contextId: 'ctx-travel', difficulty: 'medium' },
  { id: 'phrase-nearby-shopping', vocabularyItemId: 'word-nearby', text: 'Is there a mall nearby?', meaning: '근처에 쇼핑몰이 있나요?', contextId: 'ctx-shopping', difficulty: 'easy' },

  // ticket
  { id: 'phrase-ticket-transportation', vocabularyItemId: 'word-ticket', text: 'Where can I buy a ticket?', meaning: '표는 어디서 살 수 있나요?', contextId: 'ctx-transportation', difficulty: 'medium' },
  { id: 'phrase-ticket-movie', vocabularyItemId: 'word-ticket', text: 'Two tickets, please.', meaning: '표 두 장 주세요.', contextId: 'ctx-movie', difficulty: 'easy' },
  { id: 'phrase-ticket-travel', vocabularyItemId: 'word-ticket', text: 'Do I need a ticket for the bus?', meaning: '버스 타려면 표가 필요한가요?', contextId: 'ctx-travel', difficulty: 'medium' },

  // platform
  { id: 'phrase-platform-transportation', vocabularyItemId: 'word-platform', text: 'Which platform does the train leave from?', meaning: '기차가 몇 번 플랫폼에서 출발하나요?', contextId: 'ctx-transportation', difficulty: 'medium' },
  { id: 'phrase-platform-travel', vocabularyItemId: 'word-platform', text: "I can't find the right platform.", meaning: '올바른 플랫폼을 못 찾겠어요.', contextId: 'ctx-travel', difficulty: 'medium' },
  { id: 'phrase-platform-casual', vocabularyItemId: 'word-platform', text: 'Wait for me on the platform.', meaning: '플랫폼에서 기다려줘.', contextId: 'ctx-casual', difficulty: 'medium' },

  // --- Level 3 ---
  // family
  { id: 'phrase-family-family', vocabularyItemId: 'word-family', text: 'Do you have a big family?', meaning: '가족이 많으세요?', contextId: 'ctx-family', difficulty: 'medium' },
  { id: 'phrase-family-introductions', vocabularyItemId: 'word-family', text: 'My family lives in Seoul.', meaning: '저희 가족은 서울에 살아요.', contextId: 'ctx-introductions', difficulty: 'easy' },
  { id: 'phrase-family-casual', vocabularyItemId: 'word-family', text: 'I miss my family.', meaning: '가족이 그리워요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // brother
  { id: 'phrase-brother-family', vocabularyItemId: 'word-brother', text: 'I have an older brother.', meaning: '저는 형(오빠)이 있어요.', contextId: 'ctx-family', difficulty: 'easy' },
  { id: 'phrase-brother-introductions', vocabularyItemId: 'word-brother', text: 'This is my brother, Tom.', meaning: '이쪽은 제 형(오빠) Tom이에요.', contextId: 'ctx-introductions', difficulty: 'easy' },
  { id: 'phrase-brother-casual', vocabularyItemId: 'word-brother', text: 'My brother is coming to visit.', meaning: '제 형(오빠)이 방문할 예정이에요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // job
  { id: 'phrase-job-job', vocabularyItemId: 'word-job', text: "What's your job?", meaning: '직업이 뭐예요?', contextId: 'ctx-job', difficulty: 'easy' },
  { id: 'phrase-job-introductions', vocabularyItemId: 'word-job', text: 'I have a new job.', meaning: '저 새 직장을 구했어요.', contextId: 'ctx-introductions', difficulty: 'easy' },
  { id: 'phrase-job-casual', vocabularyItemId: 'word-job', text: "How's the new job going?", meaning: '새 직장은 어때요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // work
  { id: 'phrase-work-job', vocabularyItemId: 'word-work', text: 'I work in marketing.', meaning: '저는 마케팅에서 일해요.', contextId: 'ctx-job', difficulty: 'easy' },
  { id: 'phrase-work-dailyroutine', vocabularyItemId: 'word-work', text: 'I work from 9 to 6.', meaning: '저는 9시부터 6시까지 일해요.', contextId: 'ctx-daily-routine', difficulty: 'easy' },
  { id: 'phrase-work-casual', vocabularyItemId: 'word-work', text: 'Do you work on weekends?', meaning: '주말에도 일하세요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // hobby
  { id: 'phrase-hobby-hobbies', vocabularyItemId: 'word-hobby', text: "What's your hobby?", meaning: '취미가 뭐예요?', contextId: 'ctx-hobbies', difficulty: 'easy' },
  { id: 'phrase-hobby-preferences', vocabularyItemId: 'word-hobby', text: "I don't really have a hobby.", meaning: '저는 딱히 취미가 없어요.', contextId: 'ctx-preferences', difficulty: 'medium' },
  { id: 'phrase-hobby-casual', vocabularyItemId: 'word-hobby', text: 'Reading is my hobby.', meaning: '독서가 제 취미예요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // favorite
  { id: 'phrase-favorite-preferences', vocabularyItemId: 'word-favorite', text: "What's your favorite food?", meaning: '가장 좋아하는 음식이 뭐예요?', contextId: 'ctx-preferences', difficulty: 'easy' },
  { id: 'phrase-favorite-hobbies', vocabularyItemId: 'word-favorite', text: 'This is my favorite movie.', meaning: '이게 제가 제일 좋아하는 영화예요.', contextId: 'ctx-hobbies', difficulty: 'easy' },
  { id: 'phrase-favorite-casual', vocabularyItemId: 'word-favorite', text: "Who's your favorite singer?", meaning: '가장 좋아하는 가수가 누구예요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // prefer
  { id: 'phrase-prefer-preferences', vocabularyItemId: 'word-prefer', text: 'I prefer tea to coffee.', meaning: '저는 커피보다 차를 선호해요.', contextId: 'ctx-preferences', difficulty: 'easy' },
  { id: 'phrase-prefer-weather', vocabularyItemId: 'word-prefer', text: 'I prefer sunny days.', meaning: '저는 맑은 날이 더 좋아요.', contextId: 'ctx-weather', difficulty: 'easy' },
  { id: 'phrase-prefer-casual', vocabularyItemId: 'word-prefer', text: 'Which one do you prefer?', meaning: '어느 게 더 좋으세요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // usually
  { id: 'phrase-usually-dailyroutine', vocabularyItemId: 'word-usually', text: 'I usually wake up at 7.', meaning: '저는 보통 7시에 일어나요.', contextId: 'ctx-daily-routine', difficulty: 'easy' },
  { id: 'phrase-usually-weather', vocabularyItemId: 'word-usually', text: "It's usually sunny here.", meaning: '여기는 보통 날씨가 맑아요.', contextId: 'ctx-weather', difficulty: 'easy' },
  { id: 'phrase-usually-casual', vocabularyItemId: 'word-usually', text: 'I usually walk to work.', meaning: '저는 보통 걸어서 출근해요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // wake up
  { id: 'phrase-wakeup-dailyroutine', vocabularyItemId: 'word-wake-up', text: 'What time do you wake up?', meaning: '몇 시에 일어나세요?', contextId: 'ctx-daily-routine', difficulty: 'medium' },
  { id: 'phrase-wakeup-appointments', vocabularyItemId: 'word-wake-up', text: 'Wake me up before the appointment.', meaning: '예약 전에 저 좀 깨워주세요.', contextId: 'ctx-appointments', difficulty: 'medium' },
  { id: 'phrase-wakeup-casual', vocabularyItemId: 'word-wake-up', text: 'I woke up late today.', meaning: '오늘 늦게 일어났어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // weather
  { id: 'phrase-weather-weather', vocabularyItemId: 'word-weather', text: "How's the weather today?", meaning: '오늘 날씨 어때요?', contextId: 'ctx-weather', difficulty: 'easy' },
  { id: 'phrase-weather-dailyroutine', vocabularyItemId: 'word-weather', text: 'I check the weather every morning.', meaning: '저는 매일 아침 날씨를 확인해요.', contextId: 'ctx-daily-routine', difficulty: 'medium' },
  { id: 'phrase-weather-casual', vocabularyItemId: 'word-weather', text: 'The weather is perfect for a walk.', meaning: '산책하기 딱 좋은 날씨예요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // rain
  { id: 'phrase-rain-weather', vocabularyItemId: 'word-rain', text: "It's raining outside.", meaning: '밖에 비가 와요.', contextId: 'ctx-weather', difficulty: 'easy' },
  { id: 'phrase-rain-appointments', vocabularyItemId: 'word-rain', text: 'The event was cancelled because of the rain.', meaning: '비 때문에 행사가 취소됐어요.', contextId: 'ctx-appointments', difficulty: 'medium' },
  { id: 'phrase-rain-casual', vocabularyItemId: 'word-rain', text: "Don't forget your umbrella, it might rain.", meaning: '우산 챙기세요, 비 올 수도 있어요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // appointment
  { id: 'phrase-appointment-appointments', vocabularyItemId: 'word-appointment', text: "I have a doctor's appointment.", meaning: '병원 예약이 있어요.', contextId: 'ctx-appointments', difficulty: 'easy' },
  { id: 'phrase-appointment-job', vocabularyItemId: 'word-appointment', text: 'I have an appointment with a client.', meaning: '고객과 미팅이 있어요.', contextId: 'ctx-job', difficulty: 'medium' },
  { id: 'phrase-appointment-casual', vocabularyItemId: 'word-appointment', text: 'Can I reschedule my appointment?', meaning: '예약을 변경할 수 있을까요?', contextId: 'ctx-casual', difficulty: 'easy' },

  // schedule
  { id: 'phrase-schedule-appointments', vocabularyItemId: 'word-schedule', text: 'Can we schedule a meeting?', meaning: '회의 일정을 잡을 수 있을까요?', contextId: 'ctx-appointments', difficulty: 'easy' },
  { id: 'phrase-schedule-job', vocabularyItemId: 'word-schedule', text: 'My schedule is really busy this week.', meaning: '이번 주 제 일정이 정말 바빠요.', contextId: 'ctx-job', difficulty: 'medium' },
  { id: 'phrase-schedule-dailyroutine', vocabularyItemId: 'word-schedule', text: "What's your schedule for tomorrow?", meaning: '내일 일정이 어떻게 되세요?', contextId: 'ctx-daily-routine', difficulty: 'easy' },

  // --- Level 4 ---
  // friend
  { id: 'phrase-friend-friends', vocabularyItemId: 'word-friend', text: "He's my best friend.", meaning: '그는 제 가장 친한 친구예요.', contextId: 'ctx-friends', difficulty: 'easy' },
  { id: 'phrase-friend-invitations', vocabularyItemId: 'word-friend', text: 'Can I bring a friend to the party?', meaning: '파티에 친구를 데려가도 될까요?', contextId: 'ctx-invitations', difficulty: 'medium' },
  { id: 'phrase-friend-casual', vocabularyItemId: 'word-friend', text: "We've been friends since college.", meaning: '우리는 대학 때부터 친구예요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // invite
  { id: 'phrase-invite-invitations', vocabularyItemId: 'word-invite', text: "I'd like to invite you to my party.", meaning: '제 파티에 초대하고 싶어요.', contextId: 'ctx-invitations', difficulty: 'medium' },
  { id: 'phrase-invite-friends', vocabularyItemId: 'word-invite', text: 'Did you invite your friends?', meaning: '친구들 초대했어요?', contextId: 'ctx-friends', difficulty: 'easy' },
  { id: 'phrase-invite-casual', vocabularyItemId: 'word-invite', text: 'Thanks for inviting me.', meaning: '초대해줘서 고마워요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // party
  { id: 'phrase-party-invitations', vocabularyItemId: 'word-party', text: 'Are you coming to the party?', meaning: '파티에 오실 거예요?', contextId: 'ctx-invitations', difficulty: 'medium' },
  { id: 'phrase-party-weekends', vocabularyItemId: 'word-party', text: "We're having a party this weekend.", meaning: '이번 주말에 파티를 열 거예요.', contextId: 'ctx-weekends', difficulty: 'medium' },
  { id: 'phrase-party-casual', vocabularyItemId: 'word-party', text: 'The party was so much fun.', meaning: '파티가 정말 재밌었어요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // ask
  { id: 'phrase-ask-requests', vocabularyItemId: 'word-ask', text: 'Can I ask you a favor?', meaning: '부탁 하나 해도 될까요?', contextId: 'ctx-requests', difficulty: 'medium' },
  { id: 'phrase-ask-feelings', vocabularyItemId: 'word-ask', text: "Can I ask how you're feeling?", meaning: '기분이 어떤지 물어봐도 될까요?', contextId: 'ctx-feelings', difficulty: 'medium' },
  { id: 'phrase-ask-casual', vocabularyItemId: 'word-ask', text: 'She asked me a question.', meaning: '그녀가 저에게 질문을 했어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // favor
  { id: 'phrase-favor-requests', vocabularyItemId: 'word-favor', text: 'Could you do me a favor?', meaning: '부탁 하나 들어주시겠어요?', contextId: 'ctx-requests', difficulty: 'medium' },
  { id: 'phrase-favor-friends', vocabularyItemId: 'word-favor', text: 'Friends help each other with favors.', meaning: '친구들은 서로 부탁을 들어줘요.', contextId: 'ctx-friends', difficulty: 'medium' },
  { id: 'phrase-favor-casual', vocabularyItemId: 'word-favor', text: 'I owe you a favor.', meaning: '신세 졌네요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // apologize
  { id: 'phrase-apologize-apologies', vocabularyItemId: 'word-apologize', text: 'I want to apologize for yesterday.', meaning: '어제 일에 대해 사과하고 싶어요.', contextId: 'ctx-apologies', difficulty: 'medium' },
  { id: 'phrase-apologize-requests', vocabularyItemId: 'word-apologize', text: 'I apologize for asking so late.', meaning: '늦게 부탁드려서 죄송해요.', contextId: 'ctx-requests', difficulty: 'medium' },
  { id: 'phrase-apologize-casual', vocabularyItemId: 'word-apologize', text: 'He apologized right away.', meaning: '그는 바로 사과했어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // mistake
  { id: 'phrase-mistake-apologies', vocabularyItemId: 'word-mistake', text: 'I made a mistake.', meaning: '제가 실수했어요.', contextId: 'ctx-apologies', difficulty: 'easy' },
  { id: 'phrase-mistake-experiences', vocabularyItemId: 'word-mistake', text: 'It was an honest mistake.', meaning: '그건 정말 실수였어요.', contextId: 'ctx-experiences', difficulty: 'easy' },
  { id: 'phrase-mistake-casual', vocabularyItemId: 'word-mistake', text: 'Everyone makes mistakes.', meaning: '누구나 실수해요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // feel
  { id: 'phrase-feel-feelings', vocabularyItemId: 'word-feel', text: 'How do you feel today?', meaning: '오늘 기분이 어때요?', contextId: 'ctx-feelings', difficulty: 'easy' },
  { id: 'phrase-feel-experiences', vocabularyItemId: 'word-feel', text: 'How did that make you feel?', meaning: '그게 어떤 기분이 들게 했어요?', contextId: 'ctx-experiences', difficulty: 'medium' },
  { id: 'phrase-feel-casual', vocabularyItemId: 'word-feel', text: 'I feel a little tired.', meaning: '조금 피곤한 것 같아요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // excited
  { id: 'phrase-excited-feelings', vocabularyItemId: 'word-excited', text: "I'm so excited about the trip.", meaning: '여행 때문에 너무 신나요.', contextId: 'ctx-feelings', difficulty: 'medium' },
  { id: 'phrase-excited-invitations', vocabularyItemId: 'word-excited', text: "I'm excited for your party!", meaning: '당신의 파티가 너무 기대돼요!', contextId: 'ctx-invitations', difficulty: 'easy' },
  { id: 'phrase-excited-casual', vocabularyItemId: 'word-excited', text: 'She sounded really excited.', meaning: '그녀는 정말 신나 보였어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // weekend
  { id: 'phrase-weekend-weekends', vocabularyItemId: 'word-weekend', text: 'What did you do this weekend?', meaning: '이번 주말에 뭐 했어요?', contextId: 'ctx-weekends', difficulty: 'medium' },
  { id: 'phrase-weekend-friends', vocabularyItemId: 'word-weekend', text: "Let's hang out with friends this weekend.", meaning: '이번 주말에 친구들이랑 놀아요.', contextId: 'ctx-friends', difficulty: 'medium' },
  { id: 'phrase-weekend-casual', vocabularyItemId: 'word-weekend', text: 'Have a great weekend!', meaning: '좋은 주말 보내세요!', contextId: 'ctx-casual', difficulty: 'easy' },

  // relax
  { id: 'phrase-relax-weekends', vocabularyItemId: 'word-relax', text: 'I like to relax on weekends.', meaning: '저는 주말에 쉬는 걸 좋아해요.', contextId: 'ctx-weekends', difficulty: 'medium' },
  { id: 'phrase-relax-feelings', vocabularyItemId: 'word-relax', text: 'This music helps me relax.', meaning: '이 음악을 들으면 마음이 편해져요.', contextId: 'ctx-feelings', difficulty: 'easy' },
  { id: 'phrase-relax-casual', vocabularyItemId: 'word-relax', text: 'Just relax, everything will be fine.', meaning: '걱정 마세요, 다 잘 될 거예요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // experience
  { id: 'phrase-experience-experiences', vocabularyItemId: 'word-experience', text: 'That was an amazing experience.', meaning: '정말 놀라운 경험이었어요.', contextId: 'ctx-experiences', difficulty: 'easy' },
  { id: 'phrase-experience-feelings', vocabularyItemId: 'word-experience', text: 'It was a scary experience.', meaning: '무서운 경험이었어요.', contextId: 'ctx-feelings', difficulty: 'easy' },
  { id: 'phrase-experience-casual', vocabularyItemId: 'word-experience', text: 'Do you have any work experience?', meaning: '관련 경력이 있으세요?', contextId: 'ctx-casual', difficulty: 'medium' },

  // happen
  { id: 'phrase-happen-experiences', vocabularyItemId: 'word-happen', text: 'What happened yesterday?', meaning: '어제 무슨 일이 있었어요?', contextId: 'ctx-experiences', difficulty: 'easy' },
  { id: 'phrase-happen-apologies', vocabularyItemId: 'word-happen', text: "It won't happen again.", meaning: '다시는 그런 일 없을 거예요.', contextId: 'ctx-apologies', difficulty: 'easy' },
  { id: 'phrase-happen-casual', vocabularyItemId: 'word-happen', text: 'These things happen sometimes.', meaning: '그런 일은 가끔 있어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // --- Level 5 ---
  // interesting
  { id: 'phrase-interesting-interests', vocabularyItemId: 'word-interesting', text: 'That sounds interesting.', meaning: '그거 흥미롭네요.', contextId: 'ctx-interests', difficulty: 'easy' },
  { id: 'phrase-interesting-smalltalk', vocabularyItemId: 'word-interesting', text: 'Tell me something interesting about your week.', meaning: '이번 주에 있었던 흥미로운 일 얘기해 주세요.', contextId: 'ctx-small-talk', difficulty: 'medium' },
  { id: 'phrase-interesting-casual', vocabularyItemId: 'word-interesting', text: 'This book is really interesting.', meaning: '이 책 정말 흥미로워요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // curious
  { id: 'phrase-curious-interests', vocabularyItemId: 'word-curious', text: "I'm curious about your culture.", meaning: '당신의 문화가 궁금해요.', contextId: 'ctx-interests', difficulty: 'easy' },
  { id: 'phrase-curious-culture', vocabularyItemId: 'word-curious', text: "I'm curious how you celebrate that.", meaning: '그걸 어떻게 기념하는지 궁금해요.', contextId: 'ctx-culture', difficulty: 'medium' },
  { id: 'phrase-curious-casual', vocabularyItemId: 'word-curious', text: "I'm just curious, that's all.", meaning: '그냥 궁금해서 그래요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // tradition
  { id: 'phrase-tradition-culture', vocabularyItemId: 'word-tradition', text: "It's an old tradition here.", meaning: '여기의 오래된 전통이에요.', contextId: 'ctx-culture', difficulty: 'easy' },
  { id: 'phrase-tradition-travel', vocabularyItemId: 'word-tradition', text: 'We learned about a local tradition.', meaning: '현지 전통에 대해 배웠어요.', contextId: 'ctx-travel-experiences', difficulty: 'medium' },
  { id: 'phrase-tradition-casual', vocabularyItemId: 'word-tradition', text: 'My family has a fun tradition.', meaning: '저희 가족만의 재미있는 전통이 있어요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // custom
  { id: 'phrase-custom-culture', vocabularyItemId: 'word-custom', text: "That's a local custom.", meaning: '그건 현지 관습이에요.', contextId: 'ctx-culture', difficulty: 'easy' },
  { id: 'phrase-custom-travel', vocabularyItemId: 'word-custom', text: 'It’s a custom to remove your shoes here.', meaning: '여기선 신발을 벗는 게 관습이에요.', contextId: 'ctx-travel-experiences', difficulty: 'hard' },
  { id: 'phrase-custom-casual', vocabularyItemId: 'word-custom', text: 'Every family has its own customs.', meaning: '가족마다 각자의 관습이 있어요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // genre
  { id: 'phrase-genre-moviesmusic', vocabularyItemId: 'word-genre', text: 'What genre of movie do you like?', meaning: '어떤 장르의 영화를 좋아하세요?', contextId: 'ctx-movies-music', difficulty: 'medium' },
  { id: 'phrase-genre-interests', vocabularyItemId: 'word-genre', text: 'My favorite genre is comedy.', meaning: '제가 좋아하는 장르는 코미디예요.', contextId: 'ctx-interests', difficulty: 'easy' },
  { id: 'phrase-genre-casual', vocabularyItemId: 'word-genre', text: "I don't really have a favorite genre.", meaning: '저는 딱히 좋아하는 장르가 없어요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // actor
  { id: 'phrase-actor-moviesmusic', vocabularyItemId: 'word-actor', text: "Who's your favorite actor?", meaning: '가장 좋아하는 배우가 누구예요?', contextId: 'ctx-movies-music', difficulty: 'easy' },
  { id: 'phrase-actor-interests', vocabularyItemId: 'word-actor', text: 'That actor is in a lot of great films.', meaning: '그 배우는 좋은 영화에 많이 나와요.', contextId: 'ctx-interests', difficulty: 'hard' },
  { id: 'phrase-actor-casual', vocabularyItemId: 'word-actor', text: 'He wants to become an actor.', meaning: '그는 배우가 되고 싶어해요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // song
  { id: 'phrase-song-moviesmusic', vocabularyItemId: 'word-song', text: 'This song is so catchy.', meaning: '이 노래 정말 중독성 있어요.', contextId: 'ctx-movies-music', difficulty: 'easy' },
  { id: 'phrase-song-interests', vocabularyItemId: 'word-song', text: 'What song are you listening to?', meaning: '무슨 노래 듣고 있어요?', contextId: 'ctx-interests', difficulty: 'medium' },
  { id: 'phrase-song-casual', vocabularyItemId: 'word-song', text: 'That song reminds me of summer.', meaning: '그 노래를 들으면 여름이 생각나요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // delicious
  { id: 'phrase-delicious-food', vocabularyItemId: 'word-delicious', text: 'This dish is delicious.', meaning: '이 음식 정말 맛있어요.', contextId: 'ctx-food', difficulty: 'easy' },
  { id: 'phrase-delicious-travel', vocabularyItemId: 'word-delicious', text: 'The street food there was delicious.', meaning: '그곳 길거리 음식이 정말 맛있었어요.', contextId: 'ctx-travel-experiences', difficulty: 'medium' },
  { id: 'phrase-delicious-casual', vocabularyItemId: 'word-delicious', text: 'Everything smells delicious.', meaning: '다 정말 맛있는 냄새가 나요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // spicy
  { id: 'phrase-spicy-food', vocabularyItemId: 'word-spicy', text: 'Is this soup spicy?', meaning: '이 국 매워요?', contextId: 'ctx-food', difficulty: 'easy' },
  { id: 'phrase-spicy-travel', vocabularyItemId: 'word-spicy', text: 'The local food was really spicy.', meaning: '현지 음식이 정말 매웠어요.', contextId: 'ctx-travel-experiences', difficulty: 'medium' },
  { id: 'phrase-spicy-casual', vocabularyItemId: 'word-spicy', text: "I can't handle spicy food.", meaning: '저는 매운 음식을 잘 못 먹어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // abroad
  { id: 'phrase-abroad-travel', vocabularyItemId: 'word-abroad', text: 'Have you ever traveled abroad?', meaning: '해외여행 가본 적 있으세요?', contextId: 'ctx-travel-experiences', difficulty: 'easy' },
  { id: 'phrase-abroad-smalltalk', vocabularyItemId: 'word-abroad', text: "I'd love to study abroad someday.", meaning: '언젠가 해외에서 공부하고 싶어요.', contextId: 'ctx-small-talk', difficulty: 'medium' },
  { id: 'phrase-abroad-casual', vocabularyItemId: 'word-abroad', text: 'My sister lives abroad.', meaning: '제 여동생은 해외에 살아요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // memorable
  { id: 'phrase-memorable-travel', vocabularyItemId: 'word-memorable', text: 'It was a memorable trip.', meaning: '정말 기억에 남는 여행이었어요.', contextId: 'ctx-travel-experiences', difficulty: 'easy' },
  { id: 'phrase-memorable-culture', vocabularyItemId: 'word-memorable', text: 'That festival was memorable.', meaning: '그 축제는 기억에 남았어요.', contextId: 'ctx-culture', difficulty: 'easy' },
  { id: 'phrase-memorable-casual', vocabularyItemId: 'word-memorable', text: 'Yesterday was a memorable day.', meaning: '어제는 기억에 남는 하루였어요.', contextId: 'ctx-casual', difficulty: 'easy' },

  // agree
  { id: 'phrase-agree-conversation', vocabularyItemId: 'word-agree', text: 'I totally agree with you.', meaning: '전적으로 동의해요.', contextId: 'ctx-conversation', difficulty: 'easy' },
  { id: 'phrase-agree-smalltalk', vocabularyItemId: 'word-agree', text: 'Do you agree that the movie was great?', meaning: '그 영화가 좋았다는 데 동의하세요?', contextId: 'ctx-small-talk', difficulty: 'medium' },
  { id: 'phrase-agree-casual', vocabularyItemId: 'word-agree', text: "I don't really agree with that.", meaning: '저는 그거에 별로 동의하지 않아요.', contextId: 'ctx-casual', difficulty: 'medium' },

  // by the way
  { id: 'phrase-bytheway-conversation', vocabularyItemId: 'word-by-the-way', text: 'By the way, have you seen that movie?', meaning: '그런데, 그 영화 보셨어요?', contextId: 'ctx-conversation', difficulty: 'medium' },
  { id: 'phrase-bytheway-smalltalk', vocabularyItemId: 'word-by-the-way', text: "By the way, how's your family doing?", meaning: '그런데, 가족분들은 잘 지내세요?', contextId: 'ctx-small-talk', difficulty: 'medium' },
  { id: 'phrase-bytheway-casual', vocabularyItemId: 'word-by-the-way', text: 'Oh, by the way, I forgot to tell you something.', meaning: '아, 그런데 깜빡하고 말 안 한 게 있어요.', contextId: 'ctx-casual', difficulty: 'hard' },

  // --- Level 6 ---
  { id: 'phrase-home-1', vocabularyItemId: 'word-home', text: 'This is my home.', meaning: '여기가 제 집이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-home-2', vocabularyItemId: 'word-home', text: 'I want to go home now.', meaning: '이제 집에 가고 싶어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-people-1', vocabularyItemId: 'word-people', text: 'Many people live here.', meaning: '많은 사람들이 여기 살아요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-people-2', vocabularyItemId: 'word-people', text: 'She meets a lot of new people at work.', meaning: '그녀는 직장에서 새로운 사람들을 많이 만나요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-year-1', vocabularyItemId: 'word-year', text: 'This year has been busy.', meaning: '올해는 바빴어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-year-2', vocabularyItemId: 'word-year', text: 'I moved here two years ago.', meaning: '저는 2년 전에 여기로 이사했어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-health-1', vocabularyItemId: 'word-health', text: 'Health is important.', meaning: '건강은 중요해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-health-2', vocabularyItemId: 'word-health', text: 'She eats well to stay in good health.', meaning: '그녀는 건강을 유지하려고 잘 먹어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-world-1', vocabularyItemId: 'word-world', text: 'The world is big.', meaning: '세상은 넓어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-world-2', vocabularyItemId: 'word-world', text: 'He has traveled all over the world.', meaning: '그는 전 세계를 여행했어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-buy-1', vocabularyItemId: 'word-buy', text: 'I want to buy a car.', meaning: '차를 사고 싶어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-buy-2', vocabularyItemId: 'word-buy', text: 'Where did you buy those shoes?', meaning: '그 신발 어디서 샀어요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-make-1', vocabularyItemId: 'word-make', text: 'Can you make dinner?', meaning: '저녁 좀 만들어 줄래요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-make-2', vocabularyItemId: 'word-make', text: 'This factory makes toys.', meaning: '이 공장은 장난감을 만들어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-product-1', vocabularyItemId: 'word-product', text: 'This product is popular.', meaning: '이 제품은 인기가 많아요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-product-2', vocabularyItemId: 'word-product', text: 'The new product will be released next month.', meaning: '신제품은 다음 달에 출시될 거예요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-system-1', vocabularyItemId: 'word-system', text: 'The system is broken.', meaning: '시스템이 고장났어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-system-2', vocabularyItemId: 'word-system', text: 'Our school uses a new grading system.', meaning: '저희 학교는 새로운 채점 시스템을 사용해요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-city-1', vocabularyItemId: 'word-city', text: 'I live in a big city.', meaning: '저는 대도시에 살아요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-city-2', vocabularyItemId: 'word-city', text: 'The city is very busy at night.', meaning: '그 도시는 밤에 아주 붐벼요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-message-1', vocabularyItemId: 'word-message', text: 'I got your message.', meaning: '메시지 받았어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-message-2', vocabularyItemId: 'word-message', text: 'Please leave a message after the beep.', meaning: '삐 소리 후에 메시지를 남겨주세요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-good-1', vocabularyItemId: 'word-good', text: 'This is a good idea.', meaning: '좋은 생각이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-good-2', vocabularyItemId: 'word-good', text: 'She\'s very good at drawing.', meaning: '그녀는 그림을 아주 잘 그려요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-video-1', vocabularyItemId: 'word-video', text: 'I watched a funny video.', meaning: '웃긴 영상을 봤어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-video-2', vocabularyItemId: 'word-video', text: 'Can you send me the video later?', meaning: '나중에 그 영상 보내줄 수 있어요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-well-1', vocabularyItemId: 'word-well', text: 'She sings well.', meaning: '그녀는 노래를 잘해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-well-2', vocabularyItemId: 'word-well', text: 'I didn\'t sleep well last night.', meaning: '어젯밤에 잠을 잘 못 잤어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-public-1', vocabularyItemId: 'word-public', text: 'This is a public park.', meaning: '여기는 공원(공공장소)이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-public-2', vocabularyItemId: 'word-public', text: 'Smoking isn\'t allowed in public places.', meaning: '공공장소에서는 흡연이 금지돼요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-high-1', vocabularyItemId: 'word-high', text: 'The mountain is very high.', meaning: '그 산은 아주 높아요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-high-2', vocabularyItemId: 'word-high', text: 'Prices are getting higher every year.', meaning: '물가가 해마다 오르고 있어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-school-1', vocabularyItemId: 'word-school', text: 'My kids go to school.', meaning: '제 아이들은 학교에 다녀요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-school-2', vocabularyItemId: 'word-school', text: 'What time does school start?', meaning: '학교는 몇 시에 시작해요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-book-1', vocabularyItemId: 'word-book', text: 'I\'m reading a good book.', meaning: '좋은 책을 읽고 있어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-book-2', vocabularyItemId: 'word-book', text: 'Could you recommend a book for beginners?', meaning: '초보자를 위한 책 추천해 주시겠어요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-company-1', vocabularyItemId: 'word-company', text: 'She works for a big company.', meaning: '그녀는 큰 회사에서 일해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-company-2', vocabularyItemId: 'word-company', text: 'The company is hiring new employees.', meaning: '그 회사는 신입 사원을 채용하고 있어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-read-1', vocabularyItemId: 'word-read', text: 'I like to read at night.', meaning: '저는 밤에 책 읽는 걸 좋아해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-read-2', vocabularyItemId: 'word-read', text: 'Have you read this article yet?', meaning: '이 기사 읽어 봤어요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-group-1', vocabularyItemId: 'word-group', text: 'We\'re in the same group.', meaning: '우리는 같은 그룹이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-group-2', vocabularyItemId: 'word-group', text: 'The tour group met at the hotel lobby.', meaning: '여행 그룹은 호텔 로비에서 모였어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-need-1', vocabularyItemId: 'word-need', text: 'I need some help.', meaning: '도움이 필요해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-need-2', vocabularyItemId: 'word-need', text: 'Do you need anything from the store?', meaning: '가게에서 뭐 필요한 거 있어요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-life-1', vocabularyItemId: 'word-life', text: 'Life is short.', meaning: '인생은 짧아요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-life-2', vocabularyItemId: 'word-life', text: 'She\'s happy with her life right now.', meaning: '그녀는 지금의 삶에 만족해요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-way-1', vocabularyItemId: 'word-way', text: 'This is the best way.', meaning: '이게 가장 좋은 방법이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-way-2', vocabularyItemId: 'word-way', text: 'Is there another way to get there?', meaning: '거기 가는 다른 방법이 있나요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-day-1', vocabularyItemId: 'word-day', text: 'Have a nice day!', meaning: '좋은 하루 보내세요!', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-day-2', vocabularyItemId: 'word-day', text: 'What day is it today?', meaning: '오늘 무슨 요일이에요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-great-1', vocabularyItemId: 'word-great', text: 'That\'s a great idea.', meaning: '정말 좋은 생각이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-great-2', vocabularyItemId: 'word-great', text: 'We had a great time at the party.', meaning: '우리는 파티에서 정말 즐거운 시간을 보냈어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-real-1', vocabularyItemId: 'word-real', text: 'Is this a real diamond?', meaning: '이거 진짜 다이아몬드예요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-real-2', vocabularyItemId: 'word-real', text: 'That sounds like a real problem.', meaning: '그건 정말 문제인 것 같네요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-store-1', vocabularyItemId: 'word-store', text: 'I bought this at the store.', meaning: '이거 가게에서 샀어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-store-2', vocabularyItemId: 'word-store', text: 'The store closes at 9pm.', meaning: '그 가게는 밤 9시에 문 닫아요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-line-1', vocabularyItemId: 'word-line', text: 'Please wait in line.', meaning: '줄 서서 기다려 주세요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-line-2', vocabularyItemId: 'word-line', text: 'There\'s a long line at the checkout.', meaning: '계산대에 줄이 길어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-type-1', vocabularyItemId: 'word-type', text: 'What type of music do you like?', meaning: '어떤 종류의 음악을 좋아하세요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-type-2', vocabularyItemId: 'word-type', text: 'This type of phone is very popular now.', meaning: '이런 종류의 휴대폰이 요즘 인기예요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-car-1', vocabularyItemId: 'word-car', text: 'I need to fix my car.', meaning: '제 차를 고쳐야 해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-car-2', vocabularyItemId: 'word-car', text: 'Can you drop me off near my car?', meaning: '제 차 근처에 내려주실 수 있어요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-design-1', vocabularyItemId: 'word-design', text: 'She designs websites.', meaning: '그녀는 웹사이트를 디자인해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-design-2', vocabularyItemId: 'word-design', text: 'This app was designed for beginners.', meaning: '이 앱은 초보자를 위해 설계됐어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-address-1', vocabularyItemId: 'word-address', text: 'What\'s your address?', meaning: '주소가 어떻게 되세요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-address-2', vocabularyItemId: 'word-address', text: 'Could you write down your home address?', meaning: '집 주소를 적어주시겠어요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-area-1', vocabularyItemId: 'word-area', text: 'This is a quiet area.', meaning: '여기는 조용한 지역이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-area-2', vocabularyItemId: 'word-area', text: 'Is there a parking area nearby?', meaning: '근처에 주차 구역이 있나요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-want-1', vocabularyItemId: 'word-want', text: 'What do you want to eat?', meaning: '뭐 먹고 싶어요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-want-2', vocabularyItemId: 'word-want', text: 'I want to learn how to swim.', meaning: '수영하는 법을 배우고 싶어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-phone-1', vocabularyItemId: 'word-phone', text: 'Can I use your phone?', meaning: '전화 좀 써도 될까요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-phone-2', vocabularyItemId: 'word-phone', text: 'My phone battery is almost dead.', meaning: '제 휴대폰 배터리가 거의 다 됐어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-long-1', vocabularyItemId: 'word-long', text: 'It was a long day.', meaning: '긴 하루였어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-long-2', vocabularyItemId: 'word-long', text: 'How long does it take to get there?', meaning: '거기까지 가는 데 얼마나 걸려요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-change-1', vocabularyItemId: 'word-change', text: 'I need to change my plans.', meaning: '계획을 바꿔야 해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-change-2', vocabularyItemId: 'word-change', text: 'The weather can change quickly here.', meaning: '여기는 날씨가 빨리 바뀔 수 있어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-small-1', vocabularyItemId: 'word-small', text: 'It\'s a small apartment.', meaning: '작은 아파트예요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-small-2', vocabularyItemId: 'word-small', text: 'Do you have this in a smaller size?', meaning: '이거 더 작은 사이즈 있나요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-sign-1', vocabularyItemId: 'word-sign', text: 'Follow the sign to the exit.', meaning: '출구 표지판을 따라가세요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-sign-2', vocabularyItemId: 'word-sign', text: 'There\'s no sign for the restroom here.', meaning: '여기 화장실 표지판이 없어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-open-1', vocabularyItemId: 'word-open', text: 'The store is open now.', meaning: '가게가 지금 열려 있어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-open-2', vocabularyItemId: 'word-open', text: 'Is the museum open on Sundays?', meaning: '박물관이 일요일에 여나요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-case-1', vocabularyItemId: 'word-case', text: 'In that case, let\'s wait.', meaning: '그렇다면, 기다립시다.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-case-2', vocabularyItemId: 'word-case', text: 'In my case, I usually walk to work.', meaning: '제 경우엔, 보통 걸어서 출근해요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-same-1', vocabularyItemId: 'word-same', text: 'We have the same opinion.', meaning: '우리는 같은 의견이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-same-2', vocabularyItemId: 'word-same', text: 'I\'ll have the same thing, please.', meaning: '저도 같은 걸로 주세요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-own-1', vocabularyItemId: 'word-own', text: 'I have my own room.', meaning: '저만의 방이 있어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-own-2', vocabularyItemId: 'word-own', text: 'She started her own business last year.', meaning: '그녀는 작년에 자기 사업을 시작했어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-find-1', vocabularyItemId: 'word-find', text: 'I can\'t find my keys.', meaning: '열쇠를 못 찾겠어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-find-2', vocabularyItemId: 'word-find', text: 'Did you find what you were looking for?', meaning: '찾던 거 찾았어요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-house-1', vocabularyItemId: 'word-house', text: 'They bought a new house.', meaning: '그들은 새 집을 샀어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-house-2', vocabularyItemId: 'word-house', text: 'Whose house are we going to?', meaning: '우리 누구네 집에 가는 거예요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-power-1', vocabularyItemId: 'word-power', text: 'The power went out.', meaning: '정전됐어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-power-2', vocabularyItemId: 'word-power', text: 'This device doesn\'t need much power.', meaning: '이 기기는 전력이 많이 필요하지 않아요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-water-1', vocabularyItemId: 'word-water', text: 'Can I have some water?', meaning: '물 좀 주시겠어요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-water-2', vocabularyItemId: 'word-water', text: 'Don\'t forget to drink enough water.', meaning: '물 충분히 마시는 거 잊지 마세요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-history-1', vocabularyItemId: 'word-history', text: 'I love learning history.', meaning: '저는 역사 배우는 걸 좋아해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-history-2', vocabularyItemId: 'word-history', text: 'This building has a long history.', meaning: '이 건물은 오랜 역사를 가지고 있어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-size-1', vocabularyItemId: 'word-size', text: 'What size do you wear?', meaning: '어떤 사이즈 입으세요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-size-2', vocabularyItemId: 'word-size', text: 'This shirt isn\'t the right size.', meaning: '이 셔츠는 사이즈가 안 맞아요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-personal-1', vocabularyItemId: 'word-personal', text: 'That\'s a personal question.', meaning: '그건 개인적인 질문이네요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-personal-2', vocabularyItemId: 'word-personal', text: 'I\'d rather keep that personal for now.', meaning: '지금은 그건 개인적인 걸로 남겨두고 싶어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-shop-1', vocabularyItemId: 'word-shop', text: 'I like to shop on weekends.', meaning: '저는 주말에 쇼핑하는 걸 좋아해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-shop-2', vocabularyItemId: 'word-shop', text: 'We shopped for hours downtown.', meaning: '우리는 시내에서 몇 시간 동안 쇼핑했어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-white-1', vocabularyItemId: 'word-white', text: 'She wore a white dress.', meaning: '그녀는 흰 드레스를 입었어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-white-2', vocabularyItemId: 'word-white', text: 'Could I get this in white instead?', meaning: '이거 흰색으로 주실 수 있나요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-text-1', vocabularyItemId: 'word-text', text: 'I\'ll text you later.', meaning: '나중에 문자할게요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-text-2', vocabularyItemId: 'word-text', text: 'Just text me when you arrive.', meaning: '도착하면 문자만 주세요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-government-1', vocabularyItemId: 'word-government', text: 'The government made a new law.', meaning: '정부가 새 법을 만들었어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-government-2', vocabularyItemId: 'word-government', text: 'The government is planning to raise taxes.', meaning: '정부는 세금을 인상할 계획이에요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-children-1', vocabularyItemId: 'word-children', text: 'They have three children.', meaning: '그들은 아이가 셋 있어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-children-2', vocabularyItemId: 'word-children', text: 'The children are playing outside.', meaning: '아이들이 밖에서 놀고 있어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-return-1', vocabularyItemId: 'word-return', text: 'I need to return this shirt.', meaning: '이 셔츠를 반품해야 해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-return-2', vocabularyItemId: 'word-return', text: 'When are you planning to return home?', meaning: '언제 집에 돌아갈 계획이에요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-level-1', vocabularyItemId: 'word-level', text: 'This is a beginner level.', meaning: '이건 초급 레벨이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-level-2', vocabularyItemId: 'word-level', text: 'Her English level has really improved.', meaning: '그녀의 영어 실력이 정말 늘었어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-love-1', vocabularyItemId: 'word-love', text: 'I love this song.', meaning: '저는 이 노래를 정말 좋아해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-love-2', vocabularyItemId: 'word-love', text: 'She loves spending time with her family.', meaning: '그녀는 가족과 시간 보내는 걸 정말 좋아해요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-call-1', vocabularyItemId: 'word-call', text: 'Please call me tomorrow.', meaning: '내일 전화해 주세요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-call-2', vocabularyItemId: 'word-call', text: 'I\'ll call you as soon as I land.', meaning: '도착하자마자 전화할게요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-hour-1', vocabularyItemId: 'word-hour', text: 'It takes one hour.', meaning: '한 시간 걸려요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-hour-2', vocabularyItemId: 'word-hour', text: 'The meeting lasted over an hour.', meaning: '회의가 한 시간 넘게 걸렸어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-image-1', vocabularyItemId: 'word-image', text: 'This image looks blurry.', meaning: '이 이미지가 흐릿해 보여요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-image-2', vocabularyItemId: 'word-image', text: 'Can you attach the image to the email?', meaning: '이미지를 이메일에 첨부해 주시겠어요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-another-1', vocabularyItemId: 'word-another', text: 'Can I get another cup?', meaning: '한 잔 더 주시겠어요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-another-2', vocabularyItemId: 'word-another', text: 'Let\'s try another restaurant next time.', meaning: '다음엔 다른 식당에 가봐요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-money-1', vocabularyItemId: 'word-money', text: 'I don\'t have much money.', meaning: '돈이 많지 않아요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-money-2', vocabularyItemId: 'word-money', text: 'How much money did you spend?', meaning: '돈 얼마나 썼어요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-quality-1', vocabularyItemId: 'word-quality', text: 'This product has great quality.', meaning: '이 제품은 품질이 아주 좋아요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-quality-2', vocabularyItemId: 'word-quality', text: 'The quality of this coffee is amazing.', meaning: '이 커피의 품질은 정말 훌륭해요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-value-1', vocabularyItemId: 'word-value', text: 'This has great value.', meaning: '이건 가치가 아주 좋아요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-value-2', vocabularyItemId: 'word-value', text: 'The value of the house went up.', meaning: '그 집의 가치가 올랐어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-man-1', vocabularyItemId: 'word-man', text: 'That man is my neighbor.', meaning: '저 남자는 제 이웃이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-man-2', vocabularyItemId: 'word-man', text: 'The man over there is waving at you.', meaning: '저기 저 남자가 당신에게 손을 흔들고 있어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-provide-1', vocabularyItemId: 'word-provide', text: 'We provide free delivery.', meaning: '저희는 무료 배달을 제공해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-provide-2', vocabularyItemId: 'word-provide', text: 'The hotel provides breakfast every morning.', meaning: '그 호텔은 매일 아침 조식을 제공해요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-food-1', vocabularyItemId: 'word-food', text: 'I love Korean food.', meaning: '저는 한국 음식을 정말 좋아해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-food-2', vocabularyItemId: 'word-food', text: 'This restaurant serves great food.', meaning: '이 식당은 음식이 정말 맛있어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-different-1', vocabularyItemId: 'word-different', text: 'This is a different color.', meaning: '이건 다른 색이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-different-2', vocabularyItemId: 'word-different', text: 'Every country has different customs.', meaning: '나라마다 다른 관습이 있어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-learn-1', vocabularyItemId: 'word-learn', text: 'I\'m learning English.', meaning: '저는 영어를 배우고 있어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-learn-2', vocabularyItemId: 'word-learn', text: 'It\'s never too late to learn something new.', meaning: '새로운 것을 배우는 데 너무 늦은 때는 없어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-course-1', vocabularyItemId: 'word-course', text: 'I\'m taking an English course.', meaning: '저는 영어 수업을 듣고 있어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-course-2', vocabularyItemId: 'word-course', text: 'This course covers the basics of cooking.', meaning: '이 수업은 요리의 기본을 다뤄요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-room-1', vocabularyItemId: 'word-room', text: 'The room is very clean.', meaning: '방이 아주 깨끗해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-room-2', vocabularyItemId: 'word-room', text: 'Is there enough room for everyone?', meaning: '모두를 위한 공간이 충분해요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-point-1', vocabularyItemId: 'word-point', text: 'That\'s a good point.', meaning: '좋은 지적이에요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-point-2', vocabularyItemId: 'word-point', text: 'What\'s the point of doing that?', meaning: '그걸 하는 이유가 뭐예요?', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-join-1', vocabularyItemId: 'word-join', text: 'Do you want to join us?', meaning: '저희랑 같이 할래요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-join-2', vocabularyItemId: 'word-join', text: 'She joined the gym last week.', meaning: '그녀는 지난주에 헬스장에 등록했어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-science-1', vocabularyItemId: 'word-science', text: 'She studies science.', meaning: '그녀는 과학을 공부해요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-science-2', vocabularyItemId: 'word-science', text: 'He\'s always been interested in science.', meaning: '그는 항상 과학에 관심이 있었어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-team-1', vocabularyItemId: 'word-team', text: 'Our team won the game.', meaning: '우리 팀이 경기에서 이겼어요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-team-2', vocabularyItemId: 'word-team', text: 'I joined a new team at work.', meaning: '저는 회사에서 새 팀에 합류했어요.', contextId: 'ctx-casual', difficulty: 'medium' },
  { id: 'phrase-week-1', vocabularyItemId: 'word-week', text: 'See you next week.', meaning: '다음 주에 봐요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-week-2', vocabularyItemId: 'word-week', text: 'I\'m busy this whole week.', meaning: '저는 이번 주 내내 바빠요.', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-plan-1', vocabularyItemId: 'word-plan', text: 'What\'s your plan for today?', meaning: '오늘 계획이 뭐예요?', contextId: 'ctx-casual', difficulty: 'easy' },
  { id: 'phrase-plan-2', vocabularyItemId: 'word-plan', text: 'Our plans changed at the last minute.', meaning: '우리 계획이 막판에 바뀌었어요.', contextId: 'ctx-casual', difficulty: 'medium' },
];

export function phrasesForWord(vocabularyItemId: string): Phrase[] {
  return phrases.filter((p) => p.vocabularyItemId === vocabularyItemId);
}
